### PR TITLE
TR translate added to CRX version

### PR DESCRIPTION
**Pull request by zahek**

### CODE REVIEW

**Comment by GwenDragon** [comment]
Thanks :)

**Comment by zahek** [comment]
you're welcome.

**Comment by GwenDragon** [comment]
Strange that you are missing in Contributors at https://github.com/GwenDragon/searchenginepreview/graphs/contributors

**Comment by zahek** [comment]
Yes it is strange :)

**Comment by GwenDragon** [comment]
I reported that you are missing to Github support. Lets see what went wrong ;)

**Comment by GwenDragon** [comment]
@zahek  the mail address ....@oprtr.... you authored with is not registered in your Github account, said the support. 
To add one see https://help.github.com/articles/adding-an-email-address-to-your-github-account/
If you add it, you will appear as contributor ,)

**Pull request merged**
